<h1>Agrupamento com Fuzzy c-means 
<h3>Conhecido como agrupamento parcial difuso, apresenta a probabilidade das instâncias pertencerem a cada grupo

<h3>Configurando o jupyter notebook

In [1]:
#Largura de página
from IPython.core.display import display, HTML 
display(HTML("<style>.container {width:90% !important;}</style>"))

#Quantidade de colunas e linhas nos meus datasets
import pandas as pd
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 2000)

<h3>Importando as bibliotecas

In [2]:
from sklearn import datasets #datasets
import numpy as np #para cálculos matemáticos
from sklearn.metrics import confusion_matrix #matrix de confusão

#Instalar o scikit-fuzzy pelo terminal
import skfuzzy #algoritmo de agrupamento

<h3>Carregando os dados

In [3]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

<h3>Aplicando o algortimo

In [8]:
#Traz os dados que vão estar utilizando do dataset iris
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
#Faço a matrix transposta
iris.data.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

<h4>Importante: Quando trabalho com este algoritmo, a matrix de dados que vou colocar no parametro data deve ser transposta

In [10]:
#Aplico a matrix transposta no meu algortimo. Crio o objeto r (resultado)
#Parametros:c = Numero de clusters
#           m = Membership, indica qual grupo cada cluster pertence (na documentação é indico usar 2)
#           error = Erro. Critério de parada (na documentação é inidicado usar 0.005)
#           maxiter = Quantas vezes ele vai fazer as repetições
#           init = None
r = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005, maxiter = 1000, init = None)
r

(array([[6.77421528, 3.05215032, 5.6457892 , 2.05316301],
        [5.00396442, 3.41412143, 1.48276248, 0.25352252],
        [5.8882735 , 2.76083185, 4.36298923, 1.39681913]]),
 array([[1.07189623e-03, 7.50227325e-03, 6.41737432e-03, 1.01132087e-02,
         1.76787980e-03, 2.06295645e-02, 6.50745708e-03, 1.41285329e-04,
         2.19131509e-02, 5.34484309e-03, 1.02051391e-02, 2.43273522e-03,
         9.18204150e-03, 2.52461479e-02, 3.76444912e-02, 5.43251735e-02,
         1.75019114e-02, 1.05883468e-03, 3.03219840e-02, 6.65606231e-03,
         9.54619124e-03, 4.79587147e-03, 1.38368513e-02, 6.11670375e-03,
         9.84514528e-03, 7.97906119e-03, 1.57498132e-03, 2.08755092e-03,
         1.99657580e-03, 6.28665397e-03, 6.47793945e-03, 7.94390557e-03,
         2.03413146e-02, 3.23595753e-02, 4.59709701e-03, 4.80682837e-03,
         1.15684815e-02, 2.92689889e-03, 1.92413635e-02, 5.33534927e-04,
         1.68827499e-03, 4.70148331e-02, 1.52150730e-02, 6.33371906e-03,
         1.66101543e-

<h3>Separando o valores de probabilidade

In [11]:
previsoes_porcentagem = r[1]
previsoes_porcentagem

array([[1.07189623e-03, 7.50227325e-03, 6.41737432e-03, 1.01132087e-02,
        1.76787980e-03, 2.06295645e-02, 6.50745708e-03, 1.41285329e-04,
        2.19131509e-02, 5.34484309e-03, 1.02051391e-02, 2.43273522e-03,
        9.18204150e-03, 2.52461479e-02, 3.76444912e-02, 5.43251735e-02,
        1.75019114e-02, 1.05883468e-03, 3.03219840e-02, 6.65606231e-03,
        9.54619124e-03, 4.79587147e-03, 1.38368513e-02, 6.11670375e-03,
        9.84514528e-03, 7.97906119e-03, 1.57498132e-03, 2.08755092e-03,
        1.99657580e-03, 6.28665397e-03, 6.47793945e-03, 7.94390557e-03,
        2.03413146e-02, 3.23595753e-02, 4.59709701e-03, 4.80682837e-03,
        1.15684815e-02, 2.92689889e-03, 1.92413635e-02, 5.33534927e-04,
        1.68827499e-03, 4.70148331e-02, 1.52150730e-02, 6.33371906e-03,
        1.66101543e-02, 8.63648284e-03, 7.36792705e-03, 8.13074269e-03,
        7.26232607e-03, 9.19613794e-04, 5.01858516e-01, 2.07521919e-01,
        6.00841776e-01, 8.03151858e-02, 2.18008161e-01, 2.047391

In [14]:
#Posso verificar qual a probalidade do primeiro registro (instância) pertencer aos grupo 0,1 e 2
print(previsoes_porcentagem[0][0])
print(previsoes_porcentagem[1][0])
print(previsoes_porcentagem[2][0])
#De acordo com o resultado, verifico que a probabilidade deste registro pertencer apenas ao grupo 1 é muito grande sendo de 99%

0.0010718962345658875
0.9966236455943167
0.0023044581711175105


<h3>Vou considerar que o registro pertencerá ao grupo que apresentar uma maior probabilidade

In [16]:
#Crio meu objeto previsoes. Utilizo a função argmax para pegar o maior valor e defino o parametro axis=0 para pegar as colunas
previsoes = previsoes_porcentagem.argmax(axis = 0)
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2], dtype=int32)

<h3>Matrix de Confusão

In [17]:
resultados = confusion_matrix(iris.target, previsoes)
resultados

array([[ 0, 50,  0],
       [ 3,  0, 47],
       [37,  0, 13]], dtype=int64)